// MENUU — trilingual content (single source of truth)
// en = English · ms = Bahasa Melayu · zh = 中文 (简体)

export type Lang = "en" | "ms" | "zh";

export const LANGS: { id: Lang; label: string; short: string }[] = [
  { id: "en", label: "English", short: "EN" },
  { id: "ms", label: "Bahasa Melayu", short: "BM" },
  { id: "zh", label: "中文", short: "中文" },
];

export const WHATSAPP_URL =
  "https://wa.me/60167068931?text=Hi%20Vincent%2C%20saya%20berminat%20dengan%20MENUU";

export const content = {
  en: {
    nav: {
      links: [
        { label: "Problem", href: "#problem" },
        { label: "Positioning", href: "#positioning" },
        { label: "Comparison", href: "#comparison" },
        { label: "How", href: "#how" },
        { label: "Benefits", href: "#benefits" },
        { label: "Contact", href: "#contact" },
      ],
      demo: "Book Demo",
      whatsapp: "WhatsApp Vincent",
    },
    hero: {
      pill: "Malaysia's 1st pre-arrival ordering website",
      headline: "Every Restaurant Can Have Its Own Menu Website",
      sub: "MENUU helps restaurants put their full menu online, so customers can browse, decide, and send their order details before they arrive — without transaction fees or complicated setup.",
      bullets: [
        "Customers can browse your full menu online",
        "They decide what to eat before arriving",
        "Orders / enquiries go straight to your restaurant",
        "No commission or transaction fees",
        "Better first impression on Google",
      ],
      badges: ["Full Menu Website", "Mobile Friendly", "No Transaction Fees", "WhatsApp Orders", "Google Business Ready"],
      primary: "Book Demo",
      secondary: "WhatsApp Vincent",
      stats: [
        { value: "99%", label: "browse on mobile" },
        { value: "0%", label: "transaction fees" },
        { value: "First 50", label: "get a special offer" },
      ],
    },
    phone: {
      brand: "Restoran Selera Kita",
      tagline: "Authentic home-style Malaysian",
      open: "Open · 10am–10pm",
      menuTitle: "Popular Today",
      items: [
        { name: "Nasi Lemak Special", price: "RM 9.90" },
        { name: "Ayam Goreng Berempah", price: "RM 7.50" },
        { name: "Teh Tarik", price: "RM 2.50" },
      ],
      order: "Order / Enquiry",
      view: "View full menu",
    },
    problem: {
      tag: "The Problem",
      heading: "Customers are searching. But most restaurants lose them before they arrive.",
      sub: "Most restaurants already have delivery apps and dine-in QR ordering. But when customers search on Google, many still don't have a simple website menu to view, decide, and order before arriving.",
      steps: [
        { label: "Google Search", note: "Comparing nearby options" },
        { label: "Open Profile", note: "Expecting a menu or website" },
        { label: "No Menu Found", note: "Many have no proper menu", bad: true },
        { label: "Customer Leaves", note: "Checks another restaurant", bad: true },
        { label: "Finds a Menu", note: "Browses before deciding" },
        { label: "Restaurant Wins", note: "Better online menu wins" },
      ],
      phoneTitle: "Phone orders still create extra workload.",
      phoneDesc: "Regular customers or those on the way often call to ask what's available and order item by item. When staff are busy, calls get missed, orders slow down, and cashier workload increases.",
      pains: [
        "Staff too busy to pick up calls",
        "Cashier workload increases",
        "Orders missed or misunderstood",
        "Customer experience becomes slower",
        "Loses ready-to-buy customers",
      ],
      bridge: "MENUU fills this missing step — helping customers view the menu, plan their order, and send it to the restaurant before they arrive.",
    },
    positioning: {
      tag: "Positioning",
      heading: "Delivery Takes a Cut. QR Helps Dine-in. MENUU Wins Before Customers Arrive.",
      sub: "MENUU helps restaurants capture customers earlier — when they're searching on Google, checking the menu and deciding what to eat.",
      summary: "Best before arrival: MENUU",
      recommended: "Recommended",
      stages: [
        { label: "PIONEER", title: "Delivery Platform", subtitle: "Food delivery orders" },
        { label: "NEXT BRILLIANT IDEA", title: "Dine-in QR / POS", subtitle: "Order after sitting down" },
        { label: "NEXT NEW IDEA", title: "MENUU Pre-Arrival Website", subtitle: "Browse & order before arriving" },
      ],
      closing: "How MENUU Works for Your Customers",
      journey: ["Google Search", "Select Restaurant", "Menu Browsing", "Pre-Arrival Order", "Restaurant Visit"],
      tableTitle: "Quick Comparison",
      tabs: ["Compare All", "Key Differences"],
      whyBtn: "Why MENUU?",
      strip: ["0% transaction fee", "RM0/month fee", "Before customers arrive", "Found on Google"],
      cols: ["Delivery Platform", "Dine-in QR / POS", "MENUU Pre-Arrival Website"],
      colsShort: ["Delivery", "Dine-in QR", "MENUU"],
      rows: [
        { label: "Main purpose", values: ["Food delivery orders", "Customer orders after sitting down", "View menu & order before arriving"] },
        { label: "Subscription fee", values: ["NA", "From RM39/mo (QR plan usually from RM90/mo)", "RM600/year"] },
        { label: "Setup fee", values: ["NA", "Depends on provider/package", "RM399 one-time"] },
        { label: "Transaction / platform fee", values: ["30% platform fee", "1%–2% merchant charge", "0% transaction fee"] },
        { label: "Monthly fee example", values: ["RM100k × 30% = RM30,000/mo", "RM100k × 2% = RM2,000/mo", "RM100k × 0% = RM0/mo"] },
        { label: "Customer price impact", values: ["Price may rise to cover fees", "Usually same restaurant price", "Same direct restaurant price"] },
        { label: "Customer range", values: ["~10km delivery radius", "0km — inside restaurant only", "No radius limit — anyone from Google"] },
        { label: "Best timing", values: ["When customer wants delivery", "When seated (or shared to friends on the way)", "Before arrival — pre-order or direct order"] },
        { label: "Best for restaurant", values: ["Delivery exposure", "Table ordering, POS, kitchen ops", "Google visitors, menu, promos, pre-arrival"] },
        { label: "Weakness", values: ["30% fee, crowded app, platform owns customer", "Customer must arrive before ordering", "No delivery riders"] },
        { label: "Best choice for", values: ["Delivery service", "Dine-in operation", "Google discovery + pre-arrival orders"] },
      ],
    },
    benefits: {
      tag: "Benefits",
      heading: "Why MENUU stands out",
      sub: "Five ways a pre-arrival website quietly works for your restaurant.",
      items: [
        { title: "Minimise Operating Cost", desc: "No commission and lower dependence on costly third-party platforms." },
        { title: "Win Google Customers", desc: "When people find you on Google, they open your site and explore the menu instantly." },
        { title: "Let Customers ‘Menu First’", desc: "Guests decide what to eat before they reach the restaurant." },
        { title: "Improve Branding", desc: "Show your story, menu, photos and professionalism in one clean place." },
        { title: "Direct Orders, Zero Fees", desc: "Customers order or enquire directly — no third-party commission." },
      ],
    },
    demo: {
      tag: "How it works",
      heading: "See How Customers Order on Mobile",
      sub: "From the first tap to a confirmed enquiry — the whole flow lives on the phone.",
      steps: [
        "Customer opens your website",
        "The sticky order button stays visible",
        "Customer browses the menu page",
        "Customer taps the order button",
        "Order / enquiry is sent via WhatsApp",
      ],
      videoLabel: "“How to Order” demo video",
      videoNote: "Mobile walkthrough — placeholder",
      mini: ["Enter Website", "Browse Menu", "Order via Button"],
    },
    receipt: {
      tag: "Order summary",
      heading: "Clear Order Summary & Receipt",
      sub: "Customers review their order clearly, and your restaurant receives a clean, structured enquiry.",
      points: ["Customer reviews the order before sending", "Restaurant receives structured order details", "No confusion, no missed items"],
      receipt: {
        title: "MENUU Order",
        id: "Order ID",
        idValue: "#MNU-20489",
        date: "Date",
        dateValue: "29 Jun 2026",
        customer: "Customer",
        customerValue: "Aisyah Rahman",
        items: [
          { name: "Nasi Lemak Special", qty: "x2", price: "RM 19.80" },
          { name: "Ayam Goreng Berempah", qty: "x1", price: "RM 7.50" },
          { name: "Teh Tarik", qty: "x2", price: "RM 5.00" },
        ],
        total: "Total",
        totalValue: "RM 32.30",
        note: "Pickup",
        noteValue: "Self pickup · 12:30 PM",
      },
    },
    waOrder: {
      badge: "Order Summary",
      pill: "Recommended",
      tag: "Next · Best Before Arrival",
      heading: "MENUU Pre-Arrival WhatsApp Order",
      sub: "Customer sends order details before arriving",
      features: [
        { title: "Save time", desc: "Orders ready before customers arrive." },
        { title: "Reduce queues", desc: "Streamline kitchen and front-of-house flow." },
        { title: "Better experience", desc: "Personalized service from the very first step." },
      ],
      paletteLabel: "Color Palette",
      panelLabel: "WhatsApp Order Preview",
      received: "Order received",
      receivedNote: "5 min before arrival",
    },
    google: {
      tag: "Google Business Profile",
      heading: "Put Your Website on Google Business Profile",
      sub: "Customers search for food on Google, find your restaurant, click your website, and browse the menu before arriving. Better first impression, better conversion.",
      points: [
        "Customers search food on Google",
        "They find your restaurant",
        "They click your website",
        "They browse the menu before arriving",
        "Lets prospects know what you offer first",
      ],
      card: {
        name: "Restoran Selera Kita",
        rating: "4.9",
        reviews: "382 reviews",
        category: "Malaysian restaurant · RM",
        website: "Website",
        directions: "Directions",
        call: "Call",
        url: "selerakita.menuu.my",
      },
    },
    testimonials: {
      tag: "Testimonials",
      heading: "What Restaurant Owners Say About MENUU",
      sub: "Early restaurants and stalls already feel the difference.",
      items: [
        { quote: "Website MENUU sangat mesra mobile. Pelanggan tengok dulu, baru datang — senang.", name: "Hafiz", role: "Owner · Nasi Kandar stall" },
        { quote: "Pelanggan senang tengok menu dulu, jadi mereka dah tahu nak order apa.", name: "Mei Ling", role: "Cafe owner" },
        { quote: "Tiada komisen, jimat banyak kos. Imej kedai pun nampak lebih professional.", name: "Suresh", role: "Mamak restaurant" },
      ],
    },
    workload: {
      badge: "The Problem",
      headlineLead: "Phone orders still create",
      headlineAccent: "extra workload.",
      desc: "Regular customers or those on the way often call to ask what's available and order item by item. When staff are busy, calls get missed, orders slow down, and cashier workload increases.",
      pills: [
        "Staff too busy to pick up calls",
        "Cashier workload increases",
        "Orders missed or misunderstood",
        "Customer experience becomes slower",
        "Loses ready-to-buy customers",
      ],
      cards: {
        call: { title: "Incoming call", status: "Ringing…", name: "Nur", phone: "+60123456789" },
        tickets: { title: "Order tickets piling up", sub: "Too many details. Too little time.", badge: "12+" },
        overloaded: { label: "Overloaded staff.", sub: "Missed calls. Delayed orders." },
        missed: { label: "Details get missed.", sub: "Orders get messed up.", chips: ["Special request?", "Extra sauce?", "Name & number?", "…and more"] },
        ready: { label: "Lost Sales", sub: "Customers walk away before they even try your food.", menu: "MENUU", tagline: "Fresh. Fast. Easy.", order: "Order Now", confirmed: "Order confirmed!" },
      },
      cta: "Why restaurants lose customers before arrival",
    },
    market: {
      tag: "Market Opportunity",
      heading: "Most Small Restaurants Are Still Missing a Website",
      sub: "Customers search before they visit. MENUU helps small restaurants and food stalls look more ready, more trustworthy, and easier to order from — without a complicated setup.",
      points: [
        { stat: "99%", label: "of users browse on mobile" },
        { stat: "Simple", label: "setup, friendly system" },
        { stat: "99%", label: "of restaurants & stalls have no website" },
      ],
    },
    offer: {
      tag: "Limited offer",
      heading: "Special Offer for First 50 Sign Ups",
      sub: "Early adopters get a special starter offer. Limited slots available — don't miss out.",
      slots: "Only 50 slots",
      urgency: "Don't miss out",
      cta: "Claim My Slot",
    },
    contact: {
      tag: "Talk to us",
      heading: "Talk to Vincent",
      sub: "Have questions? Want to see it on your own menu? Vincent will walk you through it.",
      name: "Vincent",
      role: "Sales Executive",
      phoneLabel: "Phone",
      phone: "016-706 8931",
      addressLabel: "Address",
      address: "No 42-1, Jalan SS2/4A, Taman Sea, 47300 Petaling Jaya, Selangor",
      whatsapp: "WhatsApp Vincent",
      book: "Book Demo",
    },
    finalCta: {
      heading: "Give Your Restaurant a Better First Impression Online",
      sub: "Mobile-friendly, fee-free, and built to help customers decide before they arrive.",
      points: ["Mobile Friendly", "Decide Before Arrival", "Improve Branding", "Reduce Operating Cost", "No Transaction Fees"],
      primary: "Book Demo",
      secondary: "WhatsApp Vincent",
    },
    footer: {
      tagline: "Malaysia's first pre-arrival restaurant ordering website system.",
      website: "Website:",
      rights: "All rights reserved.",
      builtFor: "Built for restaurants & stalls in Malaysia.",
      devBy: "Development by",
    },
    stickyCta: "Book Demo",
  },

  ms: {
    nav: {
      links: [
        { label: "Masalah", href: "#problem" },
        { label: "Kedudukan", href: "#positioning" },
        { label: "Perbandingan", href: "#comparison" },
        { label: "Cara", href: "#how" },
        { label: "Manfaat", href: "#benefits" },
        { label: "Hubungi", href: "#contact" },
      ],
      demo: "Book Demo",
      whatsapp: "WhatsApp Vincent",
    },
    hero: {
      pill: "Website order pra-kedatangan pertama di Malaysia",
      headline: "Setiap Restoran Boleh Ada Website Menu Sendiri",
      sub: "MENUU bantu restoran letak menu penuh dalam talian, supaya pelanggan boleh lihat, tentukan, dan hantar butiran order sebelum tiba — tanpa caj transaksi atau setup yang rumit.",
      bullets: [
        "Pelanggan boleh lihat menu penuh dalam talian",
        "Tentukan apa nak makan sebelum sampai",
        "Order / enquiry terus ke restoran anda",
        "Tiada komisen atau caj transaksi",
        "Imej pertama lebih baik di Google",
      ],
      badges: ["Website Menu Penuh", "Mesra Mobile", "Tiada Caj Transaksi", "Order WhatsApp", "Sedia untuk Google"],
      primary: "Book Demo",
      secondary: "WhatsApp Vincent",
      stats: [
        { value: "99%", label: "layari guna mobile" },
        { value: "0%", label: "caj transaksi" },
        { value: "50 Pertama", label: "dapat tawaran khas" },
      ],
    },
    phone: {
      brand: "Restoran Selera Kita",
      tagline: "Masakan rumah Malaysia",
      open: "Buka · 10pg–10mlm",
      menuTitle: "Popular Hari Ini",
      items: [
        { name: "Nasi Lemak Special", price: "RM 9.90" },
        { name: "Ayam Goreng Berempah", price: "RM 7.50" },
        { name: "Teh Tarik", price: "RM 2.50" },
      ],
      order: "Order / Enquiry",
      view: "Lihat menu penuh",
    },
    problem: {
      tag: "Masalah",
      heading: "Pelanggan sedang mencari. Tapi kebanyakan restoran hilang mereka sebelum tiba.",
      sub: "Kebanyakan restoran sudah ada app penghantaran dan order QR dine-in. Tapi bila pelanggan cari di Google, ramai masih tiada website menu ringkas untuk lihat, tentukan dan order sebelum tiba.",
      steps: [
        { label: "Cari Google", note: "Membanding pilihan berdekatan" },
        { label: "Buka Profil", note: "Jangka ada menu atau website" },
        { label: "Menu Tiada", note: "Ramai tiada menu proper", bad: true },
        { label: "Pelanggan Pergi", note: "Semak restoran lain", bad: true },
        { label: "Jumpa Menu", note: "Layari dulu sebelum pilih" },
        { label: "Restoran Menang", note: "Menu online lebih baik menang" },
      ],
      phoneTitle: "Order telefon masih tambah beban kerja.",
      phoneDesc: "Pelanggan tetap atau yang dalam perjalanan selalu telefon untuk tanya ada apa dan order satu-satu. Bila staf sibuk, panggilan tertinggal, order jadi lambat, dan beban kaunter meningkat.",
      pains: [
        "Staf terlalu sibuk untuk jawab telefon",
        "Beban kerja kaunter meningkat",
        "Order tertinggal atau salah faham",
        "Pengalaman pelanggan jadi lambat",
        "Hilang pelanggan yang dah nak beli",
      ],
      bridge: "MENUU mengisi langkah yang hilang ini — membantu pelanggan lihat menu, rancang order, dan hantar ke restoran sebelum tiba.",
    },
    positioning: {
      tag: "Kedudukan",
      heading: "Delivery Ambil Komisen. QR Bantu Dine-in. MENUU Menang Sebelum Pelanggan Tiba.",
      sub: "MENUU bantu restoran tangkap pelanggan lebih awal — semasa mereka mencari di Google, lihat menu dan tentukan nak makan apa.",
      summary: "Terbaik sebelum tiba: MENUU",
      recommended: "Disyorkan",
      stages: [
        { label: "PELOPOR", title: "Platform Penghantaran", subtitle: "Pesanan penghantaran makanan" },
        { label: "IDEA HEBAT SETERUSNYA", title: "QR Dine-in / POS", subtitle: "Pesan selepas duduk" },
        { label: "IDEA BARU SETERUSNYA", title: "Website Pra-Tiba MENUU", subtitle: "Lihat menu & order sebelum tiba" },
      ],
      closing: "Bagaimana MENUU Berfungsi untuk Pelanggan Anda",
      journey: ["Carian Google", "Pilih Restoran", "Lihat Menu", "Order Pra-Tiba", "Tiba di Restoran"],
      tableTitle: "Perbandingan Ringkas",
      tabs: ["Bandingkan Semua", "Perbezaan Utama"],
      whyBtn: "Kenapa MENUU?",
      strip: ["Caj transaksi 0%", "Yuran RM0/bulan", "Sebelum pelanggan tiba", "Dijumpai di Google"],
      cols: ["Platform Penghantaran", "QR Dine-in / POS", "Website Pra-Tiba MENUU"],
      colsShort: ["Delivery", "QR Dine-in", "MENUU"],
      rows: [
        { label: "Tujuan utama", values: ["Pesanan penghantaran makanan", "Pelanggan order selepas duduk", "Lihat menu & order sebelum tiba"] },
        { label: "Yuran langganan", values: ["NA", "Dari RM39/bln (pelan QR biasa dari RM90/bln)", "RM600/tahun"] },
        { label: "Yuran setup", values: ["NA", "Bergantung pembekal/pakej", "RM399 sekali sahaja"] },
        { label: "Caj transaksi / platform", values: ["Caj platform 30%", "Caj merchant 1%–2%", "Caj transaksi 0%"] },
        { label: "Contoh yuran bulanan", values: ["RM100k × 30% = RM30,000/bln", "RM100k × 2% = RM2,000/bln", "RM100k × 0% = RM0/bln"] },
        { label: "Kesan harga pelanggan", values: ["Harga mungkin naik tampung yuran", "Biasanya sama harga restoran", "Sama harga restoran terus"] },
        { label: "Liputan pelanggan", values: ["Radius hantar ~10km", "0km — dalam restoran sahaja", "Tiada had radius — sesiapa dari Google"] },
        { label: "Masa terbaik", values: ["Bila pelanggan mahu delivery", "Bila duduk (atau kongsi ke kawan dalam perjalanan)", "Sebelum tiba — pra-order atau order terus"] },
        { label: "Terbaik untuk restoran", values: ["Pendedahan penghantaran", "Order meja, POS, operasi dapur", "Pelawat Google, menu, promo, pra-tiba"] },
        { label: "Kelemahan", values: ["Caj 30%, app sesak, platform milik pelanggan", "Pelanggan mesti tiba dulu", "Tiada penghantar"] },
        { label: "Pilihan terbaik untuk", values: ["Servis penghantaran", "Operasi dine-in", "Penemuan Google + order pra-tiba"] },
      ],
    },
    benefits: {
      tag: "Manfaat",
      heading: "Kenapa MENUU Menonjol",
      sub: "Lima cara website pra-kedatangan bekerja diam-diam untuk restoran anda.",
      items: [
        { title: "Kurangkan Kos Operasi", desc: "Tiada komisen dan kurang bergantung pada platform pihak ketiga yang mahal." },
        { title: "Menang Pelanggan Google", desc: "Bila orang jumpa anda di Google, mereka buka website dan terus lihat menu." },
        { title: "Biar Pelanggan ‘Menu Dulu’", desc: "Pelanggan tentukan apa nak makan sebelum sampai ke restoran." },
        { title: "Tingkatkan Branding", desc: "Tunjuk cerita, menu, gambar dan profesionalisme di satu tempat kemas." },
        { title: "Order Terus, Tiada Caj", desc: "Pelanggan order atau enquiry terus — tiada komisen pihak ketiga." },
      ],
    },
    demo: {
      tag: "Cara guna",
      heading: "Lihat Cara Pelanggan Order Guna Mobile",
      sub: "Dari sentuhan pertama hingga enquiry disahkan — semuanya dalam telefon.",
      steps: [
        "Pelanggan buka website anda",
        "Butang order sentiasa kelihatan",
        "Pelanggan layari halaman menu",
        "Pelanggan tekan butang order",
        "Order / enquiry dihantar via WhatsApp",
      ],
      videoLabel: "Video demo “Cara Order”",
      videoNote: "Panduan mobile — placeholder",
      mini: ["Masuk Website", "Layari Menu", "Order Guna Butang"],
    },
    receipt: {
      tag: "Ringkasan order",
      heading: "Ringkasan Order & Resit Yang Jelas",
      sub: "Pelanggan semak order dengan jelas, dan restoran terima enquiry yang kemas dan tersusun.",
      points: ["Pelanggan semak order sebelum hantar", "Restoran terima butiran order tersusun", "Tiada keliru, tiada item tertinggal"],
      receipt: {
        title: "Order MENUU",
        id: "ID Order",
        idValue: "#MNU-20489",
        date: "Tarikh",
        dateValue: "29 Jun 2026",
        customer: "Pelanggan",
        customerValue: "Aisyah Rahman",
        items: [
          { name: "Nasi Lemak Special", qty: "x2", price: "RM 19.80" },
          { name: "Ayam Goreng Berempah", qty: "x1", price: "RM 7.50" },
          { name: "Teh Tarik", qty: "x2", price: "RM 5.00" },
        ],
        total: "Jumlah",
        totalValue: "RM 32.30",
        note: "Ambil sendiri",
        noteValue: "Self pickup · 12:30 PM",
      },
    },
    waOrder: {
      badge: "Ringkasan Order",
      pill: "Disyorkan",
      tag: "Seterusnya · Terbaik Sebelum Tiba",
      heading: "Order WhatsApp Pra-Tiba MENUU",
      sub: "Pelanggan hantar butiran order sebelum tiba",
      features: [
        { title: "Jimat masa", desc: "Order siap sebelum pelanggan tiba." },
        { title: "Kurangkan beratur", desc: "Lancarkan aliran dapur dan kaunter." },
        { title: "Pengalaman lebih baik", desc: "Servis peribadi dari langkah pertama." },
      ],
      paletteLabel: "Palet Warna",
      panelLabel: "Pratonton Order WhatsApp",
      received: "Order diterima",
      receivedNote: "5 minit sebelum tiba",
    },
    google: {
      tag: "Google Business Profile",
      heading: "Letak Website Anda di Google Business Profile",
      sub: "Pelanggan cari makanan di Google, jumpa restoran anda, klik website, dan lihat menu sebelum sampai. Tanggapan pertama lebih baik, conversion lebih tinggi.",
      points: [
        "Pelanggan cari makanan di Google",
        "Mereka jumpa restoran anda",
        "Mereka klik website anda",
        "Mereka lihat menu sebelum sampai",
        "Prospek tahu apa anda tawarkan dahulu",
      ],
      card: {
        name: "Restoran Selera Kita",
        rating: "4.9",
        reviews: "382 ulasan",
        category: "Restoran Malaysia · RM",
        website: "Website",
        directions: "Arah",
        call: "Panggil",
        url: "selerakita.menuu.my",
      },
    },
    testimonials: {
      tag: "Testimoni",
      heading: "Apa Kata Pemilik Restoran Tentang MENUU",
      sub: "Restoran dan gerai terawal sudah rasa bezanya.",
      items: [
        { quote: "Website MENUU sangat mesra mobile. Pelanggan tengok dulu, baru datang — senang.", name: "Hafiz", role: "Pemilik · Gerai Nasi Kandar" },
        { quote: "Pelanggan senang tengok menu dulu, jadi mereka dah tahu nak order apa.", name: "Mei Ling", role: "Pemilik kafe" },
        { quote: "Tiada komisen, jimat banyak kos. Imej kedai pun nampak lebih professional.", name: "Suresh", role: "Restoran mamak" },
      ],
    },
    workload: {
      badge: "Masalah",
      headlineLead: "Order telefon masih menambah",
      headlineAccent: "beban kerja.",
      desc: "Pelanggan tetap atau yang dalam perjalanan selalu telefon untuk tanya apa yang ada dan order satu-satu. Bila staf sibuk, panggilan tertinggal, order jadi lambat, dan beban kerja kaunter meningkat.",
      pills: [
        "Staf terlalu sibuk untuk angkat panggilan",
        "Beban kerja kaunter meningkat",
        "Order tertinggal atau salah faham",
        "Pengalaman pelanggan jadi lebih lambat",
        "Hilang pelanggan yang dah sedia beli",
      ],
      cards: {
        call: { title: "Panggilan masuk", status: "Berdering…", name: "Nur", phone: "+60123456789" },
        tickets: { title: "Order tertimbun", sub: "Terlalu banyak butiran. Terlalu sikit masa.", badge: "12+" },
        overloaded: { label: "Staf terbeban.", sub: "Panggilan tertinggal. Order lambat." },
        missed: { label: "Butiran tertinggal.", sub: "Order jadi kelam-kabut.", chips: ["Permintaan khas?", "Tambah sos?", "Nama & nombor?", "…dan lagi"] },
        ready: { label: "Jualan Hilang", sub: "Pelanggan beredar sebelum sempat cuba makanan anda.", menu: "MENUU", tagline: "Segar. Pantas. Mudah.", order: "Order Sekarang", confirmed: "Order disahkan!" },
      },
      cta: "Kenapa restoran hilang pelanggan sebelum tiba",
    },
    market: {
      tag: "Peluang Pasaran",
      heading: "Kebanyakan Restoran Kecil Masih Tiada Website",
      sub: "Pelanggan mencari sebelum melawat. MENUU bantu restoran kecil dan gerai kelihatan lebih bersedia, lebih dipercayai, dan lebih mudah untuk diorder — tanpa setup yang rumit.",
      points: [
        { stat: "99%", label: "pengguna layari guna mobile" },
        { stat: "Mudah", label: "setup, sistem mesra" },
        { stat: "99%", label: "restoran & gerai tiada website" },
      ],
    },
    offer: {
      tag: "Tawaran terhad",
      heading: "Tawaran Khas untuk 50 Pendaftar Pertama",
      sub: "Pengguna terawal dapat tawaran permulaan istimewa. Slot terhad — jangan lepaskan peluang.",
      slots: "Hanya 50 slot",
      urgency: "Jangan lepaskan",
      cta: "Tempah Slot Saya",
    },
    contact: {
      tag: "Hubungi kami",
      heading: "Bercakap dengan Vincent",
      sub: "Ada soalan? Nak lihat ia pada menu anda sendiri? Vincent akan terangkan langkah demi langkah.",
      name: "Vincent",
      role: "Eksekutif Jualan",
      phoneLabel: "Telefon",
      phone: "016-706 8931",
      addressLabel: "Alamat",
      address: "No 42-1, Jalan SS2/4A, Taman Sea, 47300 Petaling Jaya, Selangor",
      whatsapp: "WhatsApp Vincent",
      book: "Book Demo",
    },
    finalCta: {
      heading: "Beri Restoran Anda Tanggapan Pertama Yang Lebih Baik di Talian",
      sub: "Mesra mobile, tanpa caj, dan dibina untuk bantu pelanggan tentukan sebelum tiba.",
      points: ["Mesra Mobile", "Tentukan Sebelum Tiba", "Tingkatkan Branding", "Kurangkan Kos Operasi", "Tiada Caj Transaksi"],
      primary: "Book Demo",
      secondary: "WhatsApp Vincent",
    },
    footer: {
      tagline: "Sistem website order restoran pra-kedatangan pertama di Malaysia.",
      website: "Laman web:",
      rights: "Hak cipta terpelihara.",
      builtFor: "Dibina untuk restoran & gerai di Malaysia.",
      devBy: "Dibangunkan oleh",
    },
    stickyCta: "Book Demo",
  },

  zh: {
    nav: {
      links: [
        { label: "问题", href: "#problem" },
        { label: "定位", href: "#positioning" },
        { label: "比较", href: "#comparison" },
        { label: "运作", href: "#how" },
        { label: "优势", href: "#benefits" },
        { label: "联系", href: "#contact" },
      ],
      demo: "预约演示",
      whatsapp: "WhatsApp Vincent",
    },
    hero: {
      pill: "马来西亚首个「到店前」点餐网站系统",
      headline: "每一间餐厅都能拥有自己的菜单网站",
      sub: "MENUU 帮助餐厅把完整菜单放到网上，让顾客在到店前就能浏览、决定，并发送点餐详情——无需交易费，也无需复杂设置。",
      bullets: [
        "顾客能在线浏览您的完整菜单",
        "到店前先决定吃什么",
        "订单 / 询问直接送到您的餐厅",
        "零佣金，零交易费",
        "在 Google 上留下更好的第一印象",
      ],
      badges: ["完整菜单网站", "手机友好", "零交易费", "WhatsApp 下单", "支持 Google"],
      primary: "预约演示",
      secondary: "WhatsApp Vincent",
      stats: [
        { value: "99%", label: "用手机浏览" },
        { value: "0%", label: "交易费" },
        { value: "前 50 名", label: "享特别优惠" },
      ],
    },
    phone: {
      brand: "我们的味道餐厅",
      tagline: "地道马来西亚家常味",
      open: "营业中 · 上午10时–晚上10时",
      menuTitle: "今日热门",
      items: [
        { name: "椰浆饭特餐", price: "RM 9.90" },
        { name: "香料炸鸡", price: "RM 7.50" },
        { name: "拉茶", price: "RM 2.50" },
      ],
      order: "下单 / 询问",
      view: "查看完整菜单",
    },
    problem: {
      tag: "痛点",
      heading: "顾客正在搜索。但多数餐厅在他们到店前就流失了。",
      sub: "多数餐厅已经有外卖 App 和堂食扫码点餐。但当顾客在 Google 搜索时，许多餐厅仍然没有一个简单的网站菜单，让顾客在到店前查看、决定并下单。",
      steps: [
        { label: "Google 搜索", note: "比较附近的选择" },
        { label: "打开档案", note: "期待看到菜单或网站" },
        { label: "找不到菜单", note: "许多没有像样的菜单", bad: true },
        { label: "顾客离开", note: "转看另一家餐厅", bad: true },
        { label: "找到菜单", note: "先浏览再决定" },
        { label: "餐厅胜出", note: "线上菜单更好的胜出" },
      ],
      phoneTitle: "电话点餐仍带来额外工作量。",
      phoneDesc: "常客或在路上的顾客常打电话问有什么、一样一样地点。员工忙的时候，电话漏接、订单变慢、收银工作量增加。",
      pains: [
        "员工太忙无法接电话",
        "收银工作量增加",
        "订单漏单或误解",
        "顾客体验变慢",
        "流失已想购买的顾客",
      ],
      bridge: "MENUU 补上这缺失的一步——帮助顾客查看菜单、规划订单，并在到店前发送给餐厅。",
    },
    positioning: {
      tag: "市场定位",
      heading: "外卖抽成。扫码只帮堂食。MENUU 在顾客到店前就赢。",
      sub: "MENUU 帮餐厅更早抓住顾客——当他们在 Google 搜索、查看菜单、决定吃什么的时候。",
      summary: "到店前最佳选择：MENUU",
      recommended: "推荐",
      stages: [
        { label: "先驱", title: "外卖平台", subtitle: "外卖配送订单" },
        { label: "下一个绝妙点子", title: "堂食扫码 / POS", subtitle: "坐下后点餐" },
        { label: "下一个新点子", title: "MENUU 到店前网站", subtitle: "到店前浏览菜单并下单" },
      ],
      closing: "MENUU 如何为您的顾客运作",
      journey: ["Google 搜索", "选择餐厅", "浏览菜单", "到店前下单", "到店用餐"],
      tableTitle: "快速对比",
      tabs: ["全部对比", "关键差异"],
      whyBtn: "为何选 MENUU？",
      strip: ["0% 交易费", "每月 RM0 费用", "顾客到店前", "在 Google 被找到"],
      cols: ["外卖平台", "堂食扫码 / POS", "MENUU 到店前网站"],
      colsShort: ["外卖", "堂食扫码", "MENUU"],
      rows: [
        { label: "主要用途", values: ["外卖配送订单", "顾客坐下后点餐", "到店前浏览菜单并下单"] },
        { label: "订阅费", values: ["无", "每月 RM39 起（扫码点餐方案通常 RM90/月起）", "每年 RM600"] },
        { label: "设置费", values: ["无", "视供应商 / 配套而定", "一次性 RM399"] },
        { label: "交易 / 平台费", values: ["30% 平台费", "1%–2% 商户费", "0% 交易费"] },
        { label: "月费示例", values: ["RM100k × 30% = RM30,000/月", "RM100k × 2% = RM2,000/月", "RM100k × 0% = RM0/月"] },
        { label: "对顾客价格影响", values: ["价格或上涨以抵消费用", "通常与餐厅同价", "与餐厅直接同价"] },
        { label: "顾客范围", values: ["约 10km 配送半径", "0km — 仅限店内", "无半径限制 — Google 上任何人"] },
        { label: "最佳时机", values: ["顾客想外卖时", "坐下后（也可分享给在路上的亲友）", "到店前 — 预订或直接下单"] },
        { label: "对餐厅最有利", values: ["外卖曝光", "桌边点餐、POS、厨房运营", "Google 访客、菜单、促销、到店前"] },
        { label: "弱点", values: ["30% 费用、拥挤 App、平台掌握顾客", "顾客须先到店才能点", "不提供骑手配送"] },
        { label: "最适合", values: ["外卖服务", "堂食运营", "Google 发现 + 到店前订单"] },
      ],
    },
    benefits: {
      tag: "好处",
      heading: "MENUU 的突出之处",
      sub: "到店前网站，默默为您的餐厅工作的五种方式。",
      items: [
        { title: "降低营运成本", desc: "零佣金，减少对高成本第三方平台的依赖。" },
        { title: "赢得 Google 顾客", desc: "当人们在 Google 找到您，便能打开网站立即浏览菜单。" },
        { title: "让顾客「先看菜单」", desc: "顾客在抵达餐厅前就决定好吃什么。" },
        { title: "提升品牌形象", desc: "在一个整洁的地方展示故事、菜单、照片与专业度。" },
        { title: "直接下单，零费用", desc: "顾客直接下单或询问——没有第三方佣金。" },
      ],
    },
    demo: {
      tag: "使用方式",
      heading: "看看顾客如何用手机下单",
      sub: "从第一次点击到确认询问——整个流程都在手机上完成。",
      steps: [
        "顾客打开您的网站",
        "常驻下单按钮始终可见",
        "顾客浏览菜单页面",
        "顾客点击下单按钮",
        "通过 WhatsApp 发送下单 / 询问",
      ],
      videoLabel: "「如何下单」演示视频",
      videoNote: "手机操作演示 — 占位",
      mini: ["进入网站", "浏览菜单", "按钮下单"],
    },
    receipt: {
      tag: "订单摘要",
      heading: "清晰的订单摘要与收据",
      sub: "顾客清楚地核对订单，您的餐厅收到整洁、结构化的询问。",
      points: ["顾客发送前先核对订单", "餐厅收到结构化的订单详情", "不混乱，不漏单"],
      receipt: {
        title: "MENUU 订单",
        id: "订单编号",
        idValue: "#MNU-20489",
        date: "日期",
        dateValue: "2026年6月29日",
        customer: "顾客",
        customerValue: "Aisyah Rahman",
        items: [
          { name: "椰浆饭特餐", qty: "x2", price: "RM 19.80" },
          { name: "香料炸鸡", qty: "x1", price: "RM 7.50" },
          { name: "拉茶", qty: "x2", price: "RM 5.00" },
        ],
        total: "总计",
        totalValue: "RM 32.30",
        note: "自取",
        noteValue: "自取 · 下午12:30",
      },
    },
    waOrder: {
      badge: "订单摘要",
      pill: "推荐",
      tag: "下一步 · 到店前最佳",
      heading: "MENUU 到店前 WhatsApp 下单",
      sub: "顾客到店前先发送订单详情",
      features: [
        { title: "节省时间", desc: "顾客到店前餐点已备好。" },
        { title: "减少排队", desc: "优化厨房与前台流程。" },
        { title: "更佳体验", desc: "从第一步就提供贴心服务。" },
      ],
      paletteLabel: "色板",
      panelLabel: "WhatsApp 订单预览",
      received: "订单已接收",
      receivedNote: "到店前 5 分钟",
    },
    google: {
      tag: "Google 商家档案",
      heading: "把您的网站放上 Google 商家档案",
      sub: "顾客在 Google 搜索美食、找到您的餐厅、点击网站，在到店前浏览菜单。更好的第一印象，更高的转化率。",
      points: [
        "顾客在 Google 搜索美食",
        "他们找到您的餐厅",
        "他们点击您的网站",
        "他们在到店前浏览菜单",
        "让潜在顾客先了解您提供什么",
      ],
      card: {
        name: "我们的味道餐厅",
        rating: "4.9",
        reviews: "382 条评价",
        category: "马来西亚餐厅 · RM",
        website: "网站",
        directions: "路线",
        call: "致电",
        url: "selerakita.menuu.my",
      },
    },
    testimonials: {
      tag: "客户评价",
      heading: "餐厅老板怎么说 MENUU",
      sub: "最早一批餐厅与摊位已经感受到不同。",
      items: [
        { quote: "MENUU 网站非常适合手机。顾客先看，再来——很方便。", name: "Hafiz", role: "老板 · 印度煎饭摊" },
        { quote: "顾客可以先看菜单，所以他们已经知道要点什么。", name: "美玲", role: "咖啡馆老板" },
        { quote: "没有佣金，省下很多成本。店面形象也更专业了。", name: "Suresh", role: "嘛嘛档" },
      ],
    },
    workload: {
      badge: "痛点",
      headlineLead: "电话点餐依然带来",
      headlineAccent: "额外负担。",
      desc: "熟客或在路上的顾客常打电话问有什么、一样一样地点。员工一忙，电话没人接、出单变慢、收银负担也随之增加。",
      pills: [
        "员工太忙，无暇接听电话",
        "收银台负担加重",
        "订单遗漏或被误解",
        "顾客体验变得更慢",
        "流失准备下单的顾客",
      ],
      cards: {
        call: { title: "来电", status: "响铃中…", name: "Nur", phone: "+60123456789" },
        tickets: { title: "订单越堆越多", sub: "细节太多。时间太少。", badge: "12+" },
        overloaded: { label: "员工超负荷。", sub: "漏接电话。出单延误。" },
        missed: { label: "细节被遗漏。", sub: "订单被搞乱。", chips: ["特别要求？", "加酱？", "姓名与电话？", "……还有更多"] },
        ready: { label: "流失的生意", sub: "顾客还没尝到您的美食就走了。", menu: "MENUU", tagline: "新鲜 · 快速 · 简单", order: "立即下单", confirmed: "订单已确认！" },
      },
      cta: "餐厅为何在顾客到店前就流失他们",
    },
    market: {
      tag: "市场机会",
      heading: "多数小餐厅仍然没有网站",
      sub: "顾客到访前会先搜索。MENUU 帮助小餐厅与摊位显得更就绪、更值得信赖、更容易下单——无需复杂设置。",
      points: [
        { stat: "99%", label: "用户用手机浏览" },
        { stat: "简单", label: "设置，友好系统" },
        { stat: "99%", label: "餐厅与摊位没有网站" },
      ],
    },
    offer: {
      tag: "限时优惠",
      heading: "前 50 名注册者专享优惠",
      sub: "早期用户享有特别的入门优惠。名额有限——别错过。",
      slots: "仅限 50 个名额",
      urgency: "别错过",
      cta: "抢占我的名额",
    },
    contact: {
      tag: "联系我们",
      heading: "联系 Vincent",
      sub: "有疑问？想看看它用在您自己的菜单上？Vincent 会一步步为您讲解。",
      name: "Vincent",
      role: "销售主管",
      phoneLabel: "电话",
      phone: "016-706 8931",
      addressLabel: "地址",
      address: "No 42-1, Jalan SS2/4A, Taman Sea, 47300 Petaling Jaya, Selangor",
      whatsapp: "WhatsApp Vincent",
      book: "预约演示",
    },
    finalCta: {
      heading: "让您的餐厅在线上拥有更好的第一印象",
      sub: "手机友好、零费用，助顾客在到店前就做好决定。",
      points: ["手机友好", "到店前决定", "提升品牌", "降低营运成本", "零交易费"],
      primary: "预约演示",
      secondary: "WhatsApp Vincent",
    },
    footer: {
      tagline: "马来西亚首个「到店前」餐厅点餐网站系统。",
      website: "网站：",
      rights: "版权所有。",
      builtFor: "为马来西亚的餐厅与摊位而打造。",
      devBy: "开发：",
    },
    stickyCta: "预约演示",
  },
} as const;

export type Dict = (typeof content)["en"];
